apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
        - name: notification-service
          image: alvinlal/notification-microservice:1.0.0
          ports:
            - containerPort: 8086
          imagePullPolicy: Always
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "smtp-service"
            - name: AWS_MAIL_SERVER_USERNAME
              value: "usernamehere"
            - name: AWS_MAIL_SERVER_PASSWORD
              value: "passwordhere"
            - name: AWS_MAIL_SERVER_FROM_ADDRESS
              value: "alvinzzz2001@gmail.com"