apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-microservice
  namespace: dev3
  labels:
    app: usermgmt-restapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:
    metadata:
      labels:
        app: usermgmt-restapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
        - name: init-redis
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of REDIS deployment"; while ! nc -z redis 6379; do sleep 1; printf "-"; done; echo -e "  >> REDIS Server has started";']
      containers:
        - name: usermgmt-restapp
          image: alvinlal/usermgmt-restapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password 
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          
