apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-nodeport-service
  namespace: dev3
  labels:
    app: usermgmt-restapp
spec:
  type: NodePort
  selector:
    app: usermgmt-restapp
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 31231